# -*- coding: utf-8 -*-
"""STAGEN I/O 處理器。

讀取 stagen.dat 輸入文件，寫入 stage_old.dat 和 stage_new.dat 輸出文件。
"""

from __future__ import annotations

from pathlib import Path
from typing import TextIO

from .data_structures import (
    GridParameters,
    StagenConfig,
)


class StagenInputReader:
    """STAGEN 輸入文件讀取器。"""

    def __init__(self, input_file: str | Path) -> None:
        """初始化讀取器。

        Args:
            input_file: 輸入文件路徑
        """
        self.input_file = Path(input_file)

    def _read_float(self, f: TextIO) -> float:
        """從文件讀取浮點數。"""
        line = f.readline().strip()
        return float(line.split()[0])

    def _read_int(self, f: TextIO) -> int:
        """從文件讀取整數。"""
        line = f.readline().strip()
        return int(line.split()[0])

    def _read_floats(self, f: TextIO, n: int) -> list[float]:
        """從文件讀取多個浮點數。"""
        line = f.readline().strip()
        parts = line.split()
        return [float(parts[i]) for i in range(min(n, len(parts)))]

    def read(self) -> StagenConfig:
        """讀取輸入文件。

        Returns:
            STAGEN 配置對象
        """
        with open(self.input_file) as f:
            # 讀取氣體性質
            rgas = self._read_float(f)
            gamma = self._read_float(f)

            # 讀取網格參數
            grid_params = GridParameters()
            line = f.readline().strip()
            parts = line.split()
            grid_params.im = int(parts[0])
            grid_params.km = int(parts[1])

            # 讀取周向擴張參數
            line = f.readline().strip()
            parts = line.split()
            grid_params.fp_rat = float(parts[0])
            grid_params.fp_max = float(parts[1])

            # 讀取跨向擴張參數
            line = f.readline().strip()
            parts = line.split()
            grid_params.fr_rat = float(parts[0])
            grid_params.fr_max = float(parts[1])

            # 讀取行數和截面數
            line = f.readline().strip()
            parts = line.split()
            nrows = int(parts[0])
            nosect = int(parts[1])

            # 讀取縮放因子
            fac_scale = self._read_float(f)

            # 創建配置
            config = StagenConfig(
                rgas=rgas,
                gamma=gamma,
                nrows=nrows,
                nosect=nosect,
                grid_params=grid_params,
                fac_scale=fac_scale,
            )

            return config


class StagenOutputWriter:
    """STAGEN 輸出文件寫入器。"""

    def __init__(self, output_dir: str | Path = ".") -> None:
        """初始化寫入器。

        Args:
            output_dir: 輸出目錄
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def write_stage_old(self, config: StagenConfig, filename: str = "stage_old.dat") -> None:
        """寫入 stage_old.dat 格式的輸出文件。

        Args:
            config: STAGEN 配置
            filename: 輸出文件名
        """
        output_file = self.output_dir / filename

        with open(output_file, "w", encoding="utf-8") as f:
            # 寫入標題
            f.write("   3D DATASET FOR MULTALL, GENERATED BY STAGEN\n")

            # 寫入控制參數
            f.write(f"{config.grid_params.im:6d}")
            f.write(f"{0:6d}")  # 佔位
            f.write(f"{config.grid_params.km:6d}")
            f.write(f"{0:6d}")  # 佔位
            f.write(f"{9000:6d}")  # NMAX
            f.write(f"{0:6d}")  # 佔位
            f.write(f"{0:6d}")  # 佔位
            f.write(f"{config.nosect:6d}")
            f.write(f"{config.nrows:6d}\n")

            # 寫入氣體性質
            f.write("   GAS PROPERTIES\n")
            f.write(f"   RGAS = {config.rgas:.6e}\n")
            f.write(f"   GAMMA = {config.gamma:.6e}\n")

    def write_stage_new(self, config: StagenConfig, filename: str = "stage_new.dat") -> None:
        """寫入 stage_new.dat 格式的輸出文件。

        Args:
            config: STAGEN 配置
            filename: 輸出文件名
        """
        output_file = self.output_dir / filename

        with open(output_file, "w", encoding="utf-8") as f:
            # 寫入標題
            f.write("DATA SET FOR 'multall' . GENERATED BY 'stagen'\n")

            # 計算 CP
            cp = config.rgas * config.gamma / (config.gamma - 1.0)

            # 寫入氣體性質
            f.write("   CP   and   GAMMA\n")
            f.write(f"{cp:16.8e} {config.gamma:16.8e}\n")

            # 寫入網格參數
            f.write("   GRID PARAMETERS\n")
            f.write(f"   IM = {config.grid_params.im}\n")
            f.write(f"   KM = {config.grid_params.km}\n")

            # 寫入行數和截面數
            f.write("   BLADE GEOMETRY\n")
            f.write(f"   NROWS = {config.nrows}\n")
            f.write(f"   NOSECT = {config.nosect}\n")

    def write_stagen_output(self, config: StagenConfig, filename: str = "stagen.out") -> None:
        """寫入 stagen.out 輸出文件。

        Args:
            config: STAGEN 配置
            filename: 輸出文件名
        """
        output_file = self.output_dir / filename

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("=" * 80 + "\n")
            f.write("STAGEN - 3D 葉片幾何生成\n")
            f.write("=" * 80 + "\n\n")

            # 氣體性質
            f.write("氣體性質:\n")
            f.write(f"  氣體常數 (RGAS) = {config.rgas:.6f} J/(kg·K)\n")
            f.write(f"  比熱比 (GAMMA)  = {config.gamma:.6f}\n")
            cp = config.rgas * config.gamma / (config.gamma - 1.0)
            f.write(f"  定壓比熱 (CP)    = {cp:.6f} J/(kg·K)\n\n")

            # 網格參數
            f.write("網格參數:\n")
            f.write(f"  周向網格點數 (IM) = {config.grid_params.im}\n")
            f.write(f"  跨向網格點數 (KM) = {config.grid_params.km}\n")
            f.write(f"  周向擴張比 (FP_RAT) = {config.grid_params.fp_rat:.3f}\n")
            f.write(f"  周向最大擴張 (FP_MAX) = {config.grid_params.fp_max:.3f}\n")
            f.write(f"  跨向擴張比 (FR_RAT) = {config.grid_params.fr_rat:.3f}\n")
            f.write(f"  跨向最大擴張 (FR_MAX) = {config.grid_params.fr_max:.3f}\n\n")

            # 幾何參數
            f.write("幾何參數:\n")
            f.write(f"  葉片排數 (NROWS) = {config.nrows}\n")
            f.write(f"  截面數 (NOSECT)  = {config.nosect}\n")
            f.write(f"  縮放因子 (FAC_SCALE) = {config.fac_scale:.6f}\n\n")

            # 葉片排資訊
            if config.blade_rows:
                f.write("葉片排資訊:\n")
                for i, row in enumerate(config.blade_rows, 1):
                    f.write(f"\n  排 {i}:\n")
                    f.write(f"    類型: {'轉子' if row.row_type == 'R' else '定子'}\n")
                    f.write(f"    葉片數: {row.n_blade}\n")
                    if row.row_type == "R":
                        f.write(f"    轉速: {row.rpm:.1f} RPM\n")
                    f.write(f"    截面數: {len(row.sections)}\n")

            f.write("\n" + "=" * 80 + "\n")


class StagenFileHandler:
    """STAGEN 文件處理器（整合讀取和寫入）。"""

    def __init__(self, input_file: str | Path, output_dir: str | Path = ".") -> None:
        """初始化文件處理器。

        Args:
            input_file: 輸入文件路徑
            output_dir: 輸出目錄
        """
        self.reader = StagenInputReader(input_file)
        self.writer = StagenOutputWriter(output_dir)

    def read_input(self) -> StagenConfig:
        """讀取輸入文件。

        Returns:
            STAGEN 配置對象
        """
        return self.reader.read()

    def write_all_outputs(self, config: StagenConfig) -> None:
        """寫入所有輸出文件。

        Args:
            config: STAGEN 配置
        """
        self.writer.write_stage_old(config)
        self.writer.write_stage_new(config)
        self.writer.write_stagen_output(config)
