# -*- coding: utf-8 -*-
"""STAGEN I/O 處理器測試。"""

from __future__ import annotations

from pathlib import Path

import pytest

from multall_turbomachinery_design.stagen.data_structures import (
    BladeRow,
    GridParameters,
    StagenConfig,
)
from multall_turbomachinery_design.stagen.io_handler import (
    StagenFileHandler,
    StagenInputReader,
    StagenOutputWriter,
)


@pytest.fixture
def sample_config() -> StagenConfig:
    """創建示例配置。"""
    config = StagenConfig(
        rgas=287.5,
        gamma=1.4,
        nrows=2,
        nosect=5,
        grid_params=GridParameters(
            im=37,
            km=11,
            fp_rat=1.25,
            fp_max=20.0,
            fr_rat=1.25,
            fr_max=20.0,
        ),
        fac_scale=1.0,
    )

    # 添加葉片排
    rotor = BladeRow(row_number=1, row_type="R", n_blade=24, rpm=10000.0)
    stator = BladeRow(row_number=2, row_type="S", n_blade=30, rpm=0.0)
    config.blade_rows = [rotor, stator]

    return config


@pytest.fixture
def temp_input_file(tmp_path: Path) -> Path:
    """創建臨時輸入文件。"""
    input_file = tmp_path / "test_input.dat"

    content = """287.5
1.4
37  11
1.25  20.0
1.25  20.0
2  5
1.0
"""

    with open(input_file, "w") as f:
        f.write(content)

    return input_file


def test_input_reader_initialization(temp_input_file: Path) -> None:
    """測試輸入讀取器初始化。"""
    reader = StagenInputReader(temp_input_file)
    assert reader.input_file == temp_input_file


def test_read_input_file(temp_input_file: Path) -> None:
    """測試讀取輸入文件。"""
    reader = StagenInputReader(temp_input_file)
    config = reader.read()

    # 檢查氣體性質
    assert config.rgas == pytest.approx(287.5)
    assert config.gamma == pytest.approx(1.4)

    # 檢查網格參數
    assert config.grid_params.im == 37
    assert config.grid_params.km == 11
    assert config.grid_params.fp_rat == pytest.approx(1.25)
    assert config.grid_params.fp_max == pytest.approx(20.0)
    assert config.grid_params.fr_rat == pytest.approx(1.25)
    assert config.grid_params.fr_max == pytest.approx(20.0)

    # 檢查行數和截面數
    assert config.nrows == 2
    assert config.nosect == 5

    # 檢查縮放因子
    assert config.fac_scale == pytest.approx(1.0)


def test_output_writer_initialization(tmp_path: Path) -> None:
    """測試輸出寫入器初始化。"""
    writer = StagenOutputWriter(tmp_path)
    assert writer.output_dir == tmp_path
    assert writer.output_dir.exists()


def test_write_stage_old(sample_config: StagenConfig, tmp_path: Path) -> None:
    """測試寫入 stage_old.dat。"""
    writer = StagenOutputWriter(tmp_path)
    writer.write_stage_old(sample_config)

    output_file = tmp_path / "stage_old.dat"
    assert output_file.exists()

    # 檢查文件內容
    with open(output_file, encoding="utf-8") as f:
        content = f.read()
        assert "3D DATASET FOR MULTALL" in content
        assert "GENERATED BY STAGEN" in content
        assert "GAS PROPERTIES" in content


def test_write_stage_new(sample_config: StagenConfig, tmp_path: Path) -> None:
    """測試寫入 stage_new.dat。"""
    writer = StagenOutputWriter(tmp_path)
    writer.write_stage_new(sample_config)

    output_file = tmp_path / "stage_new.dat"
    assert output_file.exists()

    # 檢查文件內容
    with open(output_file, encoding="utf-8") as f:
        content = f.read()
        assert "DATA SET FOR 'multall'" in content
        assert "GENERATED BY 'stagen'" in content
        assert "CP   and   GAMMA" in content
        assert "GRID PARAMETERS" in content


def test_write_stagen_output(sample_config: StagenConfig, tmp_path: Path) -> None:
    """測試寫入 stagen.out。"""
    writer = StagenOutputWriter(tmp_path)
    writer.write_stagen_output(sample_config)

    output_file = tmp_path / "stagen.out"
    assert output_file.exists()

    # 檢查文件內容
    with open(output_file, encoding="utf-8") as f:
        content = f.read()
        assert "STAGEN - 3D 葉片幾何生成" in content
        assert "氣體性質" in content
        assert "網格參數" in content
        assert "幾何參數" in content
        assert "葉片排資訊" in content


def test_write_stagen_output_gas_properties(sample_config: StagenConfig, tmp_path: Path) -> None:
    """測試 stagen.out 中的氣體性質計算。"""
    writer = StagenOutputWriter(tmp_path)
    writer.write_stagen_output(sample_config)

    output_file = tmp_path / "stagen.out"

    with open(output_file, encoding="utf-8") as f:
        content = f.read()
        # 檢查 CP 計算
        cp_expected = sample_config.rgas * sample_config.gamma / (sample_config.gamma - 1.0)
        assert f"定壓比熱 (CP)    = {cp_expected:.6f}" in content


def test_write_stagen_output_blade_rows(sample_config: StagenConfig, tmp_path: Path) -> None:
    """測試 stagen.out 中的葉片排資訊。"""
    writer = StagenOutputWriter(tmp_path)
    writer.write_stagen_output(sample_config)

    output_file = tmp_path / "stagen.out"

    with open(output_file, encoding="utf-8") as f:
        content = f.read()
        # 檢查轉子資訊
        assert "轉子" in content
        assert "葉片數: 24" in content
        assert "10000.0 RPM" in content
        # 檢查定子資訊
        assert "定子" in content
        assert "葉片數: 30" in content


def test_file_handler_initialization(temp_input_file: Path, tmp_path: Path) -> None:
    """測試文件處理器初始化。"""
    handler = StagenFileHandler(temp_input_file, tmp_path)
    assert handler.reader.input_file == temp_input_file
    assert handler.writer.output_dir == tmp_path


def test_file_handler_read_input(temp_input_file: Path, tmp_path: Path) -> None:
    """測試文件處理器讀取輸入。"""
    handler = StagenFileHandler(temp_input_file, tmp_path)
    config = handler.read_input()

    assert config.rgas == pytest.approx(287.5)
    assert config.gamma == pytest.approx(1.4)
    assert config.nrows == 2
    assert config.nosect == 5


def test_file_handler_write_all_outputs(temp_input_file: Path, tmp_path: Path) -> None:
    """測試文件處理器寫入所有輸出。"""
    handler = StagenFileHandler(temp_input_file, tmp_path)
    config = handler.read_input()
    handler.write_all_outputs(config)

    # 檢查所有輸出文件是否存在
    assert (tmp_path / "stage_old.dat").exists()
    assert (tmp_path / "stage_new.dat").exists()
    assert (tmp_path / "stagen.out").exists()


def test_output_dir_creation(tmp_path: Path) -> None:
    """測試輸出目錄自動創建。"""
    output_dir = tmp_path / "subdir" / "output"
    StagenOutputWriter(output_dir)

    assert output_dir.exists()
    assert output_dir.is_dir()


def test_custom_output_filenames(sample_config: StagenConfig, tmp_path: Path) -> None:
    """測試自定義輸出文件名。"""
    writer = StagenOutputWriter(tmp_path)

    # 使用自定義文件名
    writer.write_stage_old(sample_config, "custom_old.dat")
    writer.write_stage_new(sample_config, "custom_new.dat")
    writer.write_stagen_output(sample_config, "custom_output.txt")

    assert (tmp_path / "custom_old.dat").exists()
    assert (tmp_path / "custom_new.dat").exists()
    assert (tmp_path / "custom_output.txt").exists()
